"""add_inspections_invoices_payments_site_visits

Revision ID: 9075ee4dbe57
Revises: f38942513423
Create Date: 2025-12-10 22:38:06.658518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9075ee4dbe57'
down_revision: Union[str, None] = 'f38942513423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('inspection_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=20), nullable=True),
    sa.Column('permit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('inspection_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspector', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('inspection_id')
    )
    op.create_index(op.f('ix_inspections_business_id'), 'inspections', ['business_id'], unique=True)
    op.create_index('ix_inspections_deficiencies_gin', 'inspections', ['deficiencies'], unique=False, postgresql_using='gin')
    op.create_index('ix_inspections_extra_gin', 'inspections', ['extra'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inspections_inspection_type'), 'inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_inspections_permit_id'), 'inspections', ['permit_id'], unique=False)
    op.create_index('ix_inspections_photos_gin', 'inspections', ['photos'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inspections_project_id'), 'inspections', ['project_id'], unique=False)
    op.create_index(op.f('ix_inspections_scheduled_date'), 'inspections', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('qb_invoice_id', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('last_sync_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_business_id'), 'invoices', ['business_id'], unique=True)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index('ix_invoices_extra_gin', 'invoices', ['extra'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_line_items_gin', 'invoices', ['line_items'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_invoices_project_id'), 'invoices', ['project_id'], unique=False)
    op.create_index(op.f('ix_invoices_qb_invoice_id'), 'invoices', ['qb_invoice_id'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_sync_status'), 'invoices', ['sync_status'], unique=False)
    op.create_table('site_visits',
    sa.Column('visit_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('visit_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gps_location', sa.String(length=100), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('deficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index('ix_site_visits_attendees_gin', 'site_visits', ['attendees'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_site_visits_business_id'), 'site_visits', ['business_id'], unique=True)
    op.create_index(op.f('ix_site_visits_client_id'), 'site_visits', ['client_id'], unique=False)
    op.create_index('ix_site_visits_deficiencies_gin', 'site_visits', ['deficiencies'], unique=False, postgresql_using='gin')
    op.create_index('ix_site_visits_extra_gin', 'site_visits', ['extra'], unique=False, postgresql_using='gin')
    op.create_index('ix_site_visits_follow_up_actions_gin', 'site_visits', ['follow_up_actions'], unique=False, postgresql_using='gin')
    op.create_index('ix_site_visits_photos_gin', 'site_visits', ['photos'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_site_visits_project_id'), 'site_visits', ['project_id'], unique=False)
    op.create_index(op.f('ix_site_visits_scheduled_date'), 'site_visits', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_site_visits_status'), 'site_visits', ['status'], unique=False)
    op.create_index(op.f('ix_site_visits_visit_type'), 'site_visits', ['visit_type'], unique=False)
    op.drop_index('idx_clients_business_id', table_name='clients')
    op.create_index(op.f('ix_clients_business_id'), 'clients', ['business_id'], unique=True)
    op.add_column('payments', sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('payments', sa.Column('reference_number', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('sync_status', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('sync_error', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('last_sync_attempt', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_payments_business_id', table_name='payments')
    op.drop_index('ix_payments_qb_payment_id', table_name='payments')
    op.create_index(op.f('ix_payments_qb_payment_id'), 'payments', ['qb_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_business_id'), 'payments', ['business_id'], unique=True)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_sync_status'), 'payments', ['sync_status'], unique=False)
    op.drop_column('payments', 'qb_sync_status')
    op.drop_index('idx_permits_business_id', table_name='permits')
    op.create_index(op.f('ix_permits_business_id'), 'permits', ['business_id'], unique=True)
    op.drop_index('idx_projects_business_id', table_name='projects')
    op.create_index(op.f('ix_projects_business_id'), 'projects', ['business_id'], unique=True)
    op.create_index(op.f('ix_quickbooks_customers_cache_cached_at'), 'quickbooks_customers_cache', ['cached_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quickbooks_customers_cache_cached_at'), table_name='quickbooks_customers_cache')
    op.drop_index(op.f('ix_projects_business_id'), table_name='projects')
    op.create_index('idx_projects_business_id', 'projects', ['business_id'], unique=True)
    op.drop_index(op.f('ix_permits_business_id'), table_name='permits')
    op.create_index('idx_permits_business_id', 'permits', ['business_id'], unique=True)
    op.add_column('payments', sa.Column('qb_sync_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_sync_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_business_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_qb_payment_id'), table_name='payments')
    op.create_index('ix_payments_qb_payment_id', 'payments', ['qb_payment_id'], unique=False)
    op.create_index('idx_payments_business_id', 'payments', ['business_id'], unique=True)
    op.drop_column('payments', 'last_sync_attempt')
    op.drop_column('payments', 'sync_error')
    op.drop_column('payments', 'sync_status')
    op.drop_column('payments', 'reference_number')
    op.drop_column('payments', 'invoice_id')
    op.drop_index(op.f('ix_clients_business_id'), table_name='clients')
    op.create_index('idx_clients_business_id', 'clients', ['business_id'], unique=True)
    op.drop_index(op.f('ix_site_visits_visit_type'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_status'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_scheduled_date'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_project_id'), table_name='site_visits')
    op.drop_index('ix_site_visits_photos_gin', table_name='site_visits', postgresql_using='gin')
    op.drop_index('ix_site_visits_follow_up_actions_gin', table_name='site_visits', postgresql_using='gin')
    op.drop_index('ix_site_visits_extra_gin', table_name='site_visits', postgresql_using='gin')
    op.drop_index('ix_site_visits_deficiencies_gin', table_name='site_visits', postgresql_using='gin')
    op.drop_index(op.f('ix_site_visits_client_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_business_id'), table_name='site_visits')
    op.drop_index('ix_site_visits_attendees_gin', table_name='site_visits', postgresql_using='gin')
    op.drop_table('site_visits')
    op.drop_index(op.f('ix_invoices_sync_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_qb_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_project_id'), table_name='invoices')
    op.drop_index('ix_invoices_line_items_gin', table_name='invoices', postgresql_using='gin')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index('ix_invoices_extra_gin', table_name='invoices', postgresql_using='gin')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_business_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_scheduled_date'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_project_id'), table_name='inspections')
    op.drop_index('ix_inspections_photos_gin', table_name='inspections', postgresql_using='gin')
    op.drop_index(op.f('ix_inspections_permit_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_type'), table_name='inspections')
    op.drop_index('ix_inspections_extra_gin', table_name='inspections', postgresql_using='gin')
    op.drop_index('ix_inspections_deficiencies_gin', table_name='inspections', postgresql_using='gin')
    op.drop_index(op.f('ix_inspections_business_id'), table_name='inspections')
    op.drop_table('inspections')
    # ### end Alembic commands ###
