"""
Test business ID generation - verify triggers auto-generate IDs
"""
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from datetime import datetime, timezone
from app.config import settings
from app.db.models import Inspection, Invoice, Payment, SiteVisit

async def test_business_ids():
    """Test business ID auto-generation for all new models"""
    
    engine = create_async_engine(settings.DATABASE_URL)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    async with async_session() as session:
        print("\n" + "="*80)
        print("TESTING BUSINESS ID GENERATION")
        print("="*80)
        
        # Test 1: Inspection (INS-00001)
        print("\n" + "-"*80)
        print("TEST 1: Create Inspection (should get INS-00001 or next)")
        print("-"*80)
        
        inspection = Inspection(
            permit_id="cb847d41-955c-487c-adf0-7e5ae5c9e69c",  # Existing permit from test data
            project_id="6e1ff79c-a63d-4f6d-bec4-4c56f3c89612",  # Existing project
            inspection_type="Framing",
            status="Scheduled",
            notes="Test business ID generation"
        )
        session.add(inspection)
        await session.commit()
        await session.refresh(inspection)
        
        print(f"✅ Inspection Created:")
        print(f"   UUID: {inspection.inspection_id}")
        print(f"   Business ID: {inspection.business_id} ← Auto-generated by trigger!")
        
        # Test 2: Invoice (INV-00001)
        print("\n" + "-"*80)
        print("TEST 2: Create Invoice (should get INV-00001 or next)")
        print("-"*80)
        
        invoice = Invoice(
            project_id="6e1ff79c-a63d-4f6d-bec4-4c56f3c89612",
            client_id="9f9990c1-e217-4dd4-a68b-f983a726113c",
            invoice_number="INV-TEST-001",
            total_amount=1000.00,
            status="Draft"
        )
        session.add(invoice)
        await session.commit()
        await session.refresh(invoice)
        
        print(f"✅ Invoice Created:")
        print(f"   UUID: {invoice.invoice_id}")
        print(f"   Business ID: {invoice.business_id} ← Auto-generated by trigger!")
        
        # Test 3: Payment (PAY-00001)
        print("\n" + "-"*80)
        print("TEST 3: Create Payment (should get PAY-00001 or next)")
        print("-"*80)
        
        payment = Payment(
            invoice_id=invoice.invoice_id,
            amount=500.00,
            payment_date=datetime.now(timezone.utc),
            payment_method="Test"
        )
        session.add(payment)
        await session.commit()
        await session.refresh(payment)
        
        print(f"✅ Payment Created:")
        print(f"   UUID: {payment.payment_id}")
        print(f"   Business ID: {payment.business_id} ← Auto-generated by trigger!")
        
        # Test 4: SiteVisit (SV-00001)
        print("\n" + "-"*80)
        print("TEST 4: Create Site Visit (should get SV-00001 or next)")
        print("-"*80)
        
        site_visit = SiteVisit(
            project_id="6e1ff79c-a63d-4f6d-bec4-4c56f3c89612",
            client_id="9f9990c1-e217-4dd4-a68b-f983a726113c",
            visit_type="Test Visit",
            status="Scheduled"
        )
        session.add(site_visit)
        await session.commit()
        await session.refresh(site_visit)
        
        print(f"✅ Site Visit Created:")
        print(f"   UUID: {site_visit.visit_id}")
        print(f"   Business ID: {site_visit.business_id} ← Auto-generated by trigger!")
        
        print("\n" + "="*80)
        print("✅ ALL BUSINESS ID TESTS PASSED!")
        print("="*80)
        print("\nSummary:")
        print(f"  - Inspection: {inspection.business_id}")
        print(f"  - Invoice: {invoice.business_id}")
        print(f"  - Payment: {payment.business_id}")
        print(f"  - Site Visit: {site_visit.business_id}")
        print("\n  ✅ All triggers working correctly!")
        print("  ✅ Business IDs auto-generated on INSERT")
        print("  ✅ Sequences incrementing properly")
        print("\nNext: Phase A.2 Tasks 2.4-2.5 - Backfill existing records")
        print("="*80 + "\n")


if __name__ == "__main__":
    asyncio.run(test_business_ids())
